<?php
/**
 * Role
 *
 * PHP version 5
 *
 * @category Class
 * @package  Brave\NeucoreApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Brave Collective Core Services API
 *
 * Client library of Brave Collective Core Services API
 *
 * OpenAPI spec version: 0.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Brave\NeucoreApi\Model;
use \Brave\NeucoreApi\ObjectSerializer;

/**
 * Role Class Doc Comment
 *
 * @category Class
 * @package  Brave\NeucoreApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Role
{
    /**
     * Possible values of this enum
     */
    const APP_ADMIN = 'app-admin';
    const APP_MANAGER = 'app-manager';
    const GROUP_ADMIN = 'group-admin';
    const GROUP_MANAGER = 'group-manager';
    const USER = 'user';
    const USER_ADMIN = 'user-admin';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::APP_ADMIN,
            self::APP_MANAGER,
            self::GROUP_ADMIN,
            self::GROUP_MANAGER,
            self::USER,
            self::USER_ADMIN,
        ];
    }
}


