<?php
/**
 * ServiceConfiguration
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Brave\NeucoreApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Neucore API
 *
 * Client library of Neucore API
 *
 * The version of the OpenAPI document: 1.36.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Brave\NeucoreApi\Model;

use \ArrayAccess;
use \Brave\NeucoreApi\ObjectSerializer;

/**
 * ServiceConfiguration Class Doc Comment
 *
 * @category Class
 * @package  Brave\NeucoreApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ServiceConfiguration implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ServiceConfiguration';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'php_class' => 'string',
        'psr4_prefix' => 'string',
        'psr4_path' => 'string',
        'one_account' => 'bool',
        'required_groups' => 'int[]',
        'properties' => 'string[]',
        'show_password' => 'bool',
        'actions' => 'string[]',
        'urls' => '\Brave\NeucoreApi\Model\ServiceConfigurationURL[]',
        'text_account' => 'string',
        'text_top' => 'string',
        'text_register' => 'string',
        'text_pending' => 'string',
        'configuration_data' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'php_class' => null,
        'psr4_prefix' => null,
        'psr4_path' => null,
        'one_account' => null,
        'required_groups' => null,
        'properties' => null,
        'show_password' => null,
        'actions' => null,
        'urls' => null,
        'text_account' => null,
        'text_top' => null,
        'text_register' => null,
        'text_pending' => null,
        'configuration_data' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'php_class' => true,
		'psr4_prefix' => true,
		'psr4_path' => true,
		'one_account' => true,
		'required_groups' => true,
		'properties' => true,
		'show_password' => true,
		'actions' => true,
		'urls' => false,
		'text_account' => true,
		'text_top' => true,
		'text_register' => true,
		'text_pending' => true,
		'configuration_data' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'php_class' => 'phpClass',
        'psr4_prefix' => 'psr4Prefix',
        'psr4_path' => 'psr4Path',
        'one_account' => 'oneAccount',
        'required_groups' => 'requiredGroups',
        'properties' => 'properties',
        'show_password' => 'showPassword',
        'actions' => 'actions',
        'urls' => 'URLs',
        'text_account' => 'textAccount',
        'text_top' => 'textTop',
        'text_register' => 'textRegister',
        'text_pending' => 'textPending',
        'configuration_data' => 'configurationData'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'php_class' => 'setPhpClass',
        'psr4_prefix' => 'setPsr4Prefix',
        'psr4_path' => 'setPsr4Path',
        'one_account' => 'setOneAccount',
        'required_groups' => 'setRequiredGroups',
        'properties' => 'setProperties',
        'show_password' => 'setShowPassword',
        'actions' => 'setActions',
        'urls' => 'setUrls',
        'text_account' => 'setTextAccount',
        'text_top' => 'setTextTop',
        'text_register' => 'setTextRegister',
        'text_pending' => 'setTextPending',
        'configuration_data' => 'setConfigurationData'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'php_class' => 'getPhpClass',
        'psr4_prefix' => 'getPsr4Prefix',
        'psr4_path' => 'getPsr4Path',
        'one_account' => 'getOneAccount',
        'required_groups' => 'getRequiredGroups',
        'properties' => 'getProperties',
        'show_password' => 'getShowPassword',
        'actions' => 'getActions',
        'urls' => 'getUrls',
        'text_account' => 'getTextAccount',
        'text_top' => 'getTextTop',
        'text_register' => 'getTextRegister',
        'text_pending' => 'getTextPending',
        'configuration_data' => 'getConfigurationData'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPropertiesAllowableValues()
    {
        return [
            
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getActionsAllowableValues()
    {
        return [
            
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('php_class', $data ?? [], null);
        $this->setIfExists('psr4_prefix', $data ?? [], null);
        $this->setIfExists('psr4_path', $data ?? [], null);
        $this->setIfExists('one_account', $data ?? [], null);
        $this->setIfExists('required_groups', $data ?? [], null);
        $this->setIfExists('properties', $data ?? [], null);
        $this->setIfExists('show_password', $data ?? [], null);
        $this->setIfExists('actions', $data ?? [], null);
        $this->setIfExists('urls', $data ?? [], null);
        $this->setIfExists('text_account', $data ?? [], null);
        $this->setIfExists('text_top', $data ?? [], null);
        $this->setIfExists('text_register', $data ?? [], null);
        $this->setIfExists('text_pending', $data ?? [], null);
        $this->setIfExists('configuration_data', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['properties'] === null) {
            $invalidProperties[] = "'properties' can't be null";
        }
        if ($this->container['actions'] === null) {
            $invalidProperties[] = "'actions' can't be null";
        }
        if ($this->container['urls'] === null) {
            $invalidProperties[] = "'urls' can't be null";
        }
        if ($this->container['text_account'] === null) {
            $invalidProperties[] = "'text_account' can't be null";
        }
        if ($this->container['text_top'] === null) {
            $invalidProperties[] = "'text_top' can't be null";
        }
        if ($this->container['text_register'] === null) {
            $invalidProperties[] = "'text_register' can't be null";
        }
        if ($this->container['text_pending'] === null) {
            $invalidProperties[] = "'text_pending' can't be null";
        }
        if ($this->container['configuration_data'] === null) {
            $invalidProperties[] = "'configuration_data' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets php_class
     *
     * @return string|null
     */
    public function getPhpClass()
    {
        return $this->container['php_class'];
    }

    /**
     * Sets php_class
     *
     * @param string|null $php_class php_class
     *
     * @return self
     */
    public function setPhpClass($php_class)
    {

        if (is_null($php_class)) {
            array_push($this->openAPINullablesSetToNull, 'php_class');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('php_class', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['php_class'] = $php_class;

        return $this;
    }

    /**
     * Gets psr4_prefix
     *
     * @return string|null
     */
    public function getPsr4Prefix()
    {
        return $this->container['psr4_prefix'];
    }

    /**
     * Sets psr4_prefix
     *
     * @param string|null $psr4_prefix psr4_prefix
     *
     * @return self
     */
    public function setPsr4Prefix($psr4_prefix)
    {

        if (is_null($psr4_prefix)) {
            array_push($this->openAPINullablesSetToNull, 'psr4_prefix');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('psr4_prefix', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['psr4_prefix'] = $psr4_prefix;

        return $this;
    }

    /**
     * Gets psr4_path
     *
     * @return string|null
     */
    public function getPsr4Path()
    {
        return $this->container['psr4_path'];
    }

    /**
     * Sets psr4_path
     *
     * @param string|null $psr4_path psr4_path
     *
     * @return self
     */
    public function setPsr4Path($psr4_path)
    {

        if (is_null($psr4_path)) {
            array_push($this->openAPINullablesSetToNull, 'psr4_path');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('psr4_path', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['psr4_path'] = $psr4_path;

        return $this;
    }

    /**
     * Gets one_account
     *
     * @return bool|null
     */
    public function getOneAccount()
    {
        return $this->container['one_account'];
    }

    /**
     * Sets one_account
     *
     * @param bool|null $one_account one_account
     *
     * @return self
     */
    public function setOneAccount($one_account)
    {

        if (is_null($one_account)) {
            array_push($this->openAPINullablesSetToNull, 'one_account');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('one_account', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['one_account'] = $one_account;

        return $this;
    }

    /**
     * Gets required_groups
     *
     * @return int[]|null
     */
    public function getRequiredGroups()
    {
        return $this->container['required_groups'];
    }

    /**
     * Sets required_groups
     *
     * @param int[]|null $required_groups required_groups
     *
     * @return self
     */
    public function setRequiredGroups($required_groups)
    {

        if (is_null($required_groups)) {
            array_push($this->openAPINullablesSetToNull, 'required_groups');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('required_groups', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['required_groups'] = $required_groups;

        return $this;
    }

    /**
     * Gets properties
     *
     * @return string[]
     */
    public function getProperties()
    {
        return $this->container['properties'];
    }

    /**
     * Sets properties
     *
     * @param string[] $properties properties
     *
     * @return self
     */
    public function setProperties($properties)
    {
        $allowedValues = $this->getPropertiesAllowableValues();
        if (array_diff($properties, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'properties', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }

        if (is_null($properties)) {
            array_push($this->openAPINullablesSetToNull, 'properties');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('properties', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['properties'] = $properties;

        return $this;
    }

    /**
     * Gets show_password
     *
     * @return bool|null
     */
    public function getShowPassword()
    {
        return $this->container['show_password'];
    }

    /**
     * Sets show_password
     *
     * @param bool|null $show_password show_password
     *
     * @return self
     */
    public function setShowPassword($show_password)
    {

        if (is_null($show_password)) {
            array_push($this->openAPINullablesSetToNull, 'show_password');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('show_password', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['show_password'] = $show_password;

        return $this;
    }

    /**
     * Gets actions
     *
     * @return string[]
     */
    public function getActions()
    {
        return $this->container['actions'];
    }

    /**
     * Sets actions
     *
     * @param string[] $actions actions
     *
     * @return self
     */
    public function setActions($actions)
    {
        $allowedValues = $this->getActionsAllowableValues();
        if (array_diff($actions, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'actions', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }

        if (is_null($actions)) {
            array_push($this->openAPINullablesSetToNull, 'actions');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('actions', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['actions'] = $actions;

        return $this;
    }

    /**
     * Gets urls
     *
     * @return \Brave\NeucoreApi\Model\ServiceConfigurationURL[]
     */
    public function getUrls()
    {
        return $this->container['urls'];
    }

    /**
     * Sets urls
     *
     * @param \Brave\NeucoreApi\Model\ServiceConfigurationURL[] $urls urls
     *
     * @return self
     */
    public function setUrls($urls)
    {

        if (is_null($urls)) {
            throw new \InvalidArgumentException('non-nullable urls cannot be null');
        }

        $this->container['urls'] = $urls;

        return $this;
    }

    /**
     * Gets text_account
     *
     * @return string
     */
    public function getTextAccount()
    {
        return $this->container['text_account'];
    }

    /**
     * Sets text_account
     *
     * @param string $text_account text_account
     *
     * @return self
     */
    public function setTextAccount($text_account)
    {

        if (is_null($text_account)) {
            array_push($this->openAPINullablesSetToNull, 'text_account');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text_account', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['text_account'] = $text_account;

        return $this;
    }

    /**
     * Gets text_top
     *
     * @return string
     */
    public function getTextTop()
    {
        return $this->container['text_top'];
    }

    /**
     * Sets text_top
     *
     * @param string $text_top text_top
     *
     * @return self
     */
    public function setTextTop($text_top)
    {

        if (is_null($text_top)) {
            array_push($this->openAPINullablesSetToNull, 'text_top');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text_top', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['text_top'] = $text_top;

        return $this;
    }

    /**
     * Gets text_register
     *
     * @return string
     */
    public function getTextRegister()
    {
        return $this->container['text_register'];
    }

    /**
     * Sets text_register
     *
     * @param string $text_register text_register
     *
     * @return self
     */
    public function setTextRegister($text_register)
    {

        if (is_null($text_register)) {
            array_push($this->openAPINullablesSetToNull, 'text_register');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text_register', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['text_register'] = $text_register;

        return $this;
    }

    /**
     * Gets text_pending
     *
     * @return string
     */
    public function getTextPending()
    {
        return $this->container['text_pending'];
    }

    /**
     * Sets text_pending
     *
     * @param string $text_pending text_pending
     *
     * @return self
     */
    public function setTextPending($text_pending)
    {

        if (is_null($text_pending)) {
            array_push($this->openAPINullablesSetToNull, 'text_pending');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text_pending', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['text_pending'] = $text_pending;

        return $this;
    }

    /**
     * Gets configuration_data
     *
     * @return string
     */
    public function getConfigurationData()
    {
        return $this->container['configuration_data'];
    }

    /**
     * Sets configuration_data
     *
     * @param string $configuration_data configuration_data
     *
     * @return self
     */
    public function setConfigurationData($configuration_data)
    {

        if (is_null($configuration_data)) {
            throw new \InvalidArgumentException('non-nullable configuration_data cannot be null');
        }

        $this->container['configuration_data'] = $configuration_data;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


