<?php
/**
 * CorporationMemberTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Brave\NeucoreApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Brave Collective Core Services API
 *
 * Client library of Brave Collective Core Services API
 *
 * OpenAPI spec version: 0.6.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Brave\NeucoreApi;

/**
 * CorporationMemberTest Class Doc Comment
 *
 * @category    Class */
// * @description The player property contains only id and name, character does not contain corporation.
/**
 * @package     Brave\NeucoreApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CorporationMemberTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CorporationMember"
     */
    public function testCorporationMember()
    {
    }

    /**
     * Test attribute "player"
     */
    public function testPropertyPlayer()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {
    }

    /**
     * Test attribute "logoff_date"
     */
    public function testPropertyLogoffDate()
    {
    }

    /**
     * Test attribute "logon_date"
     */
    public function testPropertyLogonDate()
    {
    }

    /**
     * Test attribute "ship_type_id"
     */
    public function testPropertyShipTypeId()
    {
    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "character"
     */
    public function testPropertyCharacter()
    {
    }
}
