<?php
/**
 * PlayerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Brave\NeucoreApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Neucore API
 *
 * Client library of Neucore API
 *
 * OpenAPI spec version: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Brave\NeucoreApi;

/**
 * PlayerTest Class Doc Comment
 *
 * @category    Class
 * @description Player
 * @package     Brave\NeucoreApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PlayerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Player"
     */
    public function testPlayer()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "roles"
     */
    public function testPropertyRoles()
    {
    }

    /**
     * Test attribute "characters"
     */
    public function testPropertyCharacters()
    {
    }

    /**
     * Test attribute "groups"
     */
    public function testPropertyGroups()
    {
    }

    /**
     * Test attribute "manager_groups"
     */
    public function testPropertyManagerGroups()
    {
    }

    /**
     * Test attribute "manager_apps"
     */
    public function testPropertyManagerApps()
    {
    }

    /**
     * Test attribute "removed_characters"
     */
    public function testPropertyRemovedCharacters()
    {
    }
}
