<?php
/**
 * RemovedCharacterTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Brave\NeucoreApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Neucore API
 *
 * Client library of Neucore API
 *
 * OpenAPI spec version: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Brave\NeucoreApi;

/**
 * RemovedCharacterTest Class Doc Comment
 *
 * @category    Class
 * @description RemovedCharacter
 * @package     Brave\NeucoreApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class RemovedCharacterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RemovedCharacter"
     */
    public function testRemovedCharacter()
    {
    }

    /**
     * Test attribute "new_player_id"
     */
    public function testPropertyNewPlayerId()
    {
    }

    /**
     * Test attribute "new_player_name"
     */
    public function testPropertyNewPlayerName()
    {
    }

    /**
     * Test attribute "character_id"
     */
    public function testPropertyCharacterId()
    {
    }

    /**
     * Test attribute "character_name"
     */
    public function testPropertyCharacterName()
    {
    }

    /**
     * Test attribute "removed_date"
     */
    public function testPropertyRemovedDate()
    {
    }

    /**
     * Test attribute "reason"
     */
    public function testPropertyReason()
    {
    }
}
