<?php
/**
 * ApplicationESIApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Brave\NeucoreApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Neucore API
 *
 * Client library of Neucore API
 *
 * The version of the OpenAPI document: 1.14.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Brave\NeucoreApi;

use \Brave\NeucoreApi\Configuration;
use \Brave\NeucoreApi\ApiException;
use \Brave\NeucoreApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ApplicationESIApiTest Class Doc Comment
 *
 * @category Class
 * @package  Brave\NeucoreApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ApplicationESIApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for esiPostV1
     *
     * Same as GET /app/v1/esi, but for POST requests..
     *
     */
    public function testEsiPostV1()
    {
    }

    /**
     * Test case for esiV1
     *
     * Makes an ESI GET request on behalf on an EVE character and returns the result..
     *
     */
    public function testEsiV1()
    {
    }
}
