<?php
/**
 * ApplicationESIApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Brave\NeucoreApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Neucore API
 *
 * Client library of Neucore API
 *
 * The version of the OpenAPI document: 1.33.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Brave\NeucoreApi\Test\Api;

use \Brave\NeucoreApi\Configuration;
use \Brave\NeucoreApi\ApiException;
use \Brave\NeucoreApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ApplicationESIApiTest Class Doc Comment
 *
 * @category Class
 * @package  Brave\NeucoreApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ApplicationESIApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for esiEveLoginCharactersV1
     *
     * Returns character IDs of characters that have a valid ESI token of the specified EVE login..
     *
     */
    public function testEsiEveLoginCharactersV1()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for esiPostV1
     *
     * See POST /app/v2/esi.
     *
     */
    public function testEsiPostV1()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for esiPostV2
     *
     * Same as GET /app/v2/esi, but for POST requests..
     *
     */
    public function testEsiPostV2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for esiV1
     *
     * See GET /app/v2/esi.
     *
     */
    public function testEsiV1()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for esiV2
     *
     * Makes an ESI GET request on behalf on an EVE character and returns the result..
     *
     */
    public function testEsiV2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
