<?php
/**
 * ApplicationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Brave\NeucoreApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Brave Collective Core Services API
 *
 * Client library of Brave Collective Core Services API
 *
 * OpenAPI spec version: 0.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Brave\NeucoreApi;

use \Brave\NeucoreApi\Configuration;
use \Brave\NeucoreApi\ApiException;
use \Brave\NeucoreApi\ObjectSerializer;

/**
 * ApplicationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Brave\NeucoreApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ApplicationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for corpGroupsBulkV1
     *
     * Return groups for multiple corporations..
     *
     */
    public function testCorpGroupsBulkV1()
    {
    }

    /**
     * Test case for corpGroupsV1
     *
     * Return groups for the corporation..
     *
     */
    public function testCorpGroupsV1()
    {
    }

    /**
     * Test case for groupsBulkV1
     *
     * Return groups of multiple players, identified by one of their character IDs..
     *
     */
    public function testGroupsBulkV1()
    {
    }

    /**
     * Test case for groupsV1
     *
     * Return groups of the character's player account..
     *
     */
    public function testGroupsV1()
    {
    }

    /**
     * Test case for mainV1
     *
     * Returns the main character of the player account to which the character ID belongs..
     *
     */
    public function testMainV1()
    {
    }

    /**
     * Test case for showV1
     *
     * Show app information..
     *
     */
    public function testShowV1()
    {
    }
}
