<?php
/**
 * ApplicationGroupsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Brave\NeucoreApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Neucore API
 *
 * Client library of Neucore API
 *
 * The version of the OpenAPI document: 1.14.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Brave\NeucoreApi;

use \Brave\NeucoreApi\Configuration;
use \Brave\NeucoreApi\ApiException;
use \Brave\NeucoreApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ApplicationGroupsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Brave\NeucoreApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ApplicationGroupsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for allianceGroupsBulkV1
     *
     * Return groups of multiple alliances..
     *
     */
    public function testAllianceGroupsBulkV1()
    {
    }

    /**
     * Test case for allianceGroupsV1
     *
     * Return groups of the alliance..
     *
     */
    public function testAllianceGroupsV1()
    {
    }

    /**
     * Test case for allianceGroupsV2
     *
     * Return groups of the alliance..
     *
     */
    public function testAllianceGroupsV2()
    {
    }

    /**
     * Test case for corpGroupsBulkV1
     *
     * Return groups of multiple corporations..
     *
     */
    public function testCorpGroupsBulkV1()
    {
    }

    /**
     * Test case for corpGroupsV1
     *
     * Return groups of the corporation..
     *
     */
    public function testCorpGroupsV1()
    {
    }

    /**
     * Test case for corpGroupsV2
     *
     * Return groups of the corporation..
     *
     */
    public function testCorpGroupsV2()
    {
    }

    /**
     * Test case for groupsBulkV1
     *
     * Return groups of multiple players, identified by one of their character IDs..
     *
     */
    public function testGroupsBulkV1()
    {
    }

    /**
     * Test case for groupsV1
     *
     * Return groups of the character's player account..
     *
     */
    public function testGroupsV1()
    {
    }

    /**
     * Test case for groupsV2
     *
     * Return groups of the character's player account..
     *
     */
    public function testGroupsV2()
    {
    }

    /**
     * Test case for groupsWithFallbackV1
     *
     * Returns groups from the character's account, if available, or the corporation and alliance..
     *
     */
    public function testGroupsWithFallbackV1()
    {
    }
}
