<?php
/**
 * ApplicationCharactersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Brave\NeucoreApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Neucore API
 *
 * Client library of Neucore API
 *
 * The version of the OpenAPI document: 1.14.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Brave\NeucoreApi;

use \Brave\NeucoreApi\Configuration;
use \Brave\NeucoreApi\ApiException;
use \Brave\NeucoreApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ApplicationCharactersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Brave\NeucoreApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ApplicationCharactersApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for characterListV1
     *
     * Returns all known characters from the parameter list..
     *
     */
    public function testCharacterListV1()
    {
    }

    /**
     * Test case for charactersV1
     *
     * Returns all characters of the player account to which the character ID belongs..
     *
     */
    public function testCharactersV1()
    {
    }

    /**
     * Test case for corporationCharactersV1
     *
     * Returns a list of all known characters from the corporation..
     *
     */
    public function testCorporationCharactersV1()
    {
    }

    /**
     * Test case for corporationPlayersV1
     *
     * Returns a list of all players that have a character in the corporation..
     *
     */
    public function testCorporationPlayersV1()
    {
    }

    /**
     * Test case for incomingCharactersV1
     *
     * Returns all characters that were moved from another account to the player account to which the                     ID belongs..
     *
     */
    public function testIncomingCharactersV1()
    {
    }

    /**
     * Test case for mainV1
     *
     * Returns the main character of the player account to which the character ID belongs..
     *
     */
    public function testMainV1()
    {
    }

    /**
     * Test case for mainV2
     *
     * Returns the main character of the player account to which the character ID belongs..
     *
     */
    public function testMainV2()
    {
    }

    /**
     * Test case for playerCharactersV1
     *
     * Returns all characters from the player account..
     *
     */
    public function testPlayerCharactersV1()
    {
    }

    /**
     * Test case for playerV1
     *
     * Returns the player account to which the character ID belongs..
     *
     */
    public function testPlayerV1()
    {
    }

    /**
     * Test case for playerWithCharactersV1
     *
     * Returns the player account to which the character ID belongs with all characters..
     *
     */
    public function testPlayerWithCharactersV1()
    {
    }

    /**
     * Test case for removedCharactersV1
     *
     * Returns all characters that were removed from the player account to which the character ID                     belongs..
     *
     */
    public function testRemovedCharactersV1()
    {
    }
}
